# NOTE - This workflow is meant to be run locally using act. It is not intended to be run on GitHub Actions.
#  If you want to run it on GitHub Actions, please use the workflow in .github/workflows/e2e.yml instead.
name: act-e2e
on: workflow_dispatch
jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          python-version: '3.11.14'
          artifactory-url: ${{ vars.ARTIFACTORY_URL }}
          artifactory-repo: ${{ vars.ARTIFACTORY_REPO }}
          artifactory-token: ${{ secrets.ARTIFACTORY_TOKEN }}
      - run: python3 --version

